name: Run Tests

on:
  push:
    branches:
      - develop

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, redis, igbinary, msgpack, lzf, zstd, lz4, memcached, gmp, :php-psr
          tools: composer:v2

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run Tests
        run: ./vendor/bin/phpunit tests --color